
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2017-02-05T11:49:01.305+05:30
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeoIPService",
                      portName = "GeoIPServiceHttpGet",
                      targetNamespace = "http://www.webservicex.net/",
                      wsdlLocation = "http://www.webservicex.net/geoipservice.asmx?WSDL",
                      endpointInterface = "net.webservicex.GeoIPServiceHttpGet")
                      
public class GeoIPServiceHttpGetImpl implements GeoIPServiceHttpGet {

    private static final Logger LOG = Logger.getLogger(GeoIPServiceHttpGetImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpGet#getGeoIP(java.lang.String  ipAddress )*
     */
    public net.webservicex.GeoIP getGeoIP(java.lang.String ipAddress) { 
        LOG.info("Executing operation getGeoIP");
        System.out.println(ipAddress);
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(-1688173008);
            _return.setIP("IP-1964968375");
            _return.setReturnCodeDetails("ReturnCodeDetails611082222");
            _return.setCountryName("CountryName1547269423");
            _return.setCountryCode("CountryCode-380905194");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpGet#getGeoIPContext(*
     */
    public net.webservicex.GeoIP getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(-1786791009);
            _return.setIP("IP1251562239");
            _return.setReturnCodeDetails("ReturnCodeDetails-269082102");
            _return.setCountryName("CountryName331659461");
            _return.setCountryCode("CountryCode868365996");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
