
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2017-02-05T11:56:39.671+05:30
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeoIPService",
                      portName = "GeoIPServiceHttpPost",
                      targetNamespace = "http://www.webservicex.net/",
                      wsdlLocation = "http://www.webservicex.net/geoipservice.asmx?WSDL",
                      endpointInterface = "net.webservicex.GeoIPServiceHttpPost")
                      
public class GeoIPServiceHttpPostImpl implements GeoIPServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(GeoIPServiceHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpPost#getGeoIP(java.lang.String  ipAddress )*
     */
    public net.webservicex.GeoIP getGeoIP(java.lang.String ipAddress) { 
        LOG.info("Executing operation getGeoIP");
        System.out.println(ipAddress);
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(1456799973);
            _return.setIP("IP-2124405018");
            _return.setReturnCodeDetails("ReturnCodeDetails-103871160");
            _return.setCountryName("CountryName-299910132");
            _return.setCountryCode("CountryCode488642633");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpPost#getGeoIPContext(*
     */
    public net.webservicex.GeoIP getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(1112519698);
            _return.setIP("IP-73235724");
            _return.setReturnCodeDetails("ReturnCodeDetails469585143");
            _return.setCountryName("CountryName1262424190");
            _return.setCountryCode("CountryCode-1116827625");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
