
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2017-02-05T11:56:39.645+05:30
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeoIPService",
                      portName = "GeoIPServiceSoap12",
                      targetNamespace = "http://www.webservicex.net/",
                      wsdlLocation = "http://www.webservicex.net/geoipservice.asmx?WSDL",
                      endpointInterface = "net.webservicex.GeoIPServiceSoap")
                      
public class GeoIPServiceSoapImpl1 implements GeoIPServiceSoap {

    private static final Logger LOG = Logger.getLogger(GeoIPServiceSoapImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceSoap#getGeoIP(java.lang.String  ipAddress )*
     */
    public net.webservicex.GeoIP getGeoIP(java.lang.String ipAddress) { 
        LOG.info("Executing operation getGeoIP");
        System.out.println(ipAddress);
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(185319397);
            _return.setIP("IP661442967");
            _return.setReturnCodeDetails("ReturnCodeDetails-966585639");
            _return.setCountryName("CountryName-1805025442");
            _return.setCountryCode("CountryCode1387663141");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceSoap#getGeoIPContext(*
     */
    public net.webservicex.GeoIP getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(-1587502300);
            _return.setIP("IP-83239012");
            _return.setReturnCodeDetails("ReturnCodeDetails160830505");
            _return.setCountryName("CountryName915583105");
            _return.setCountryCode("CountryCode264912183");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
