
/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

package net.webservicex;

import java.util.logging.Logger;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.4
 * 2017-02-04T00:57:39.408+05:30
 * Generated source version: 2.7.4
 * 
 */

@javax.jws.WebService(
                      serviceName = "GeoIPService",
                      portName = "GeoIPServiceHttpPost",
                      targetNamespace = "http://www.webservicex.net/",
                      wsdlLocation = "http://www.webservicex.net/geoipservice.asmx?WSDL",
                      endpointInterface = "net.webservicex.GeoIPServiceHttpPost")
                      
public class GeoIPServiceHttpPostImpl implements GeoIPServiceHttpPost {

    private static final Logger LOG = Logger.getLogger(GeoIPServiceHttpPostImpl.class.getName());

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpPost#getGeoIP(java.lang.String  ipAddress )*
     */
    public net.webservicex.GeoIP getGeoIP(java.lang.String ipAddress) { 
        LOG.info("Executing operation getGeoIP");
        System.out.println(ipAddress);
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(-1862525692);
            _return.setIP("IP-1249972905");
            _return.setReturnCodeDetails("ReturnCodeDetails1545500714");
            _return.setCountryName("CountryName-186860849");
            _return.setCountryCode("CountryCode499361680");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

    /* (non-Javadoc)
     * @see net.webservicex.GeoIPServiceHttpPost#getGeoIPContext(*
     */
    public net.webservicex.GeoIP getGeoIPContext() { 
        LOG.info("Executing operation getGeoIPContext");
        try {
            net.webservicex.GeoIP _return = new net.webservicex.GeoIP();
            _return.setReturnCode(-2013368681);
            _return.setIP("IP904498950");
            _return.setReturnCodeDetails("ReturnCodeDetails-1870497327");
            _return.setCountryName("CountryName454611018");
            _return.setCountryCode("CountryCode1719996956");
            return _return;
        } catch (java.lang.Exception ex) {
            ex.printStackTrace();
            throw new RuntimeException(ex);
        }
    }

}
